# Run only on the following branches
branches:
  only:
    - master

# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "18"

# Cache node_modules between builds
cache:
  - node_modules -> package.json, appveyor.yml

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

before_test:
  # For now, running puppeteer on Windows does not make sense, as Chrome ignores non-webstore extensions anyway.
  #- set "PATH=C:\Program Files (x86)\Google\Chrome\Application;%PATH%"
  #- set "CHROME_BIN=chrome"
  - set "DEBUG=true"
  - set "FILE_CHECK_DELAY=2500"

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Post-test scripts
on_failure:
  - 7z a failed-test.zip %APPVEYOR_BUILD_FOLDER%\test*.zip
  - 7z a failed-test.zip %APPVEYOR_BUILD_FOLDER%\test*.crx
  - 7z a failed-test.zip %APPVEYOR_BUILD_FOLDER%\test*.xml
  - appveyor PushArtifact failed-test.zip

# Don't actually build.
build: off
