version: v1.0
name: Test Linux
agent:
  machine:
    type: a1-standard-4
    os_image: macos-mojave-xcode11
blocks:
  - name: Test
    task:
      prologue:
        commands:
          - install-package p7zip-full
          - sem-version node 12.11.1
          - checkout
          - cache restore
          - npm install
          - cache store
      jobs:
        - name: Test
          commands:
            - npm test
      epilogue:
        on_fail:
          commands:
            - 7z a failed-test.zip test*.zip test*.crx test*.xml
            - artifact push job failed-test.zip
execution_time_limit:
  minutes: 1
