/* eslint-disable */
// code generated by pbf v4.0.1

exports.writeCrxFileHeader = writeCrxFileHeader;
function writeCrxFileHeader(obj, pbf) {
    if (obj.sha256_with_rsa) for (const item of obj.sha256_with_rsa) pbf.writeMessage(2, writeAsymmetricKeyProof, item);
    if (obj.sha256_with_ecdsa) for (const item of obj.sha256_with_ecdsa) pbf.writeMessage(3, writeAsymmetricKeyProof, item);
    if (obj.verified_contents != null) pbf.writeBytesField(4, obj.verified_contents);
    if (obj.signed_header_data != null) pbf.writeBytesField(10000, obj.signed_header_data);
}

exports.writeAsymmetricKeyProof = writeAsymmetricKeyProof;
function writeAsymmetricKeyProof(obj, pbf) {
    if (obj.public_key != null) pbf.writeBytesField(1, obj.public_key);
    if (obj.signature != null) pbf.writeBytesField(2, obj.signature);
}

exports.writeSignedData = writeSignedData;
function writeSignedData(obj, pbf) {
    if (obj.crx_id != null) pbf.writeBytesField(1, obj.crx_id);
}
