/* eslint-disable */
'use strict'; // code generated by pbf v3.2.1

// CrxFileHeader ========================================

var CrxFileHeader = exports.CrxFileHeader = {};

CrxFileHeader.write = function (obj, pbf) {
    if (obj.sha256_with_rsa) for (var i = 0; i < obj.sha256_with_rsa.length; i++) pbf.writeMessage(2, AsymmetricKeyProof.write, obj.sha256_with_rsa[i]);
    if (obj.sha256_with_ecdsa) for (i = 0; i < obj.sha256_with_ecdsa.length; i++) pbf.writeMessage(3, AsymmetricKeyProof.write, obj.sha256_with_ecdsa[i]);
    if (obj.signed_header_data) pbf.writeBytesField(10000, obj.signed_header_data);
};

// AsymmetricKeyProof ========================================

var AsymmetricKeyProof = exports.AsymmetricKeyProof = {};

AsymmetricKeyProof.write = function (obj, pbf) {
    if (obj.public_key) pbf.writeBytesField(1, obj.public_key);
    if (obj.signature) pbf.writeBytesField(2, obj.signature);
};

// SignedData ========================================

var SignedData = exports.SignedData = {};

SignedData.write = function (obj, pbf) {
    if (obj.crx_id) pbf.writeBytesField(1, obj.crx_id);
};
